---
- name: Demonstrate Ansible facts
  hosts: dbservers
  gather_facts: yes  # Enable fact gathering, this is enabled by default

  tasks:
    - name: Display the operating system
      debug:
        msg: "The operating system is: {{ ansible_os_family }}"

    - name: Display the total memory
      debug:
        msg: "The total memory is: {{ ansible_memtotal_mb }} MB"

    - name: Display the IP address
      debug:
        msg: "The IP address is: {{ ansible_default_ipv4.address }}"

    - name: Display the hostname
      debug:
        msg: "The hostname is: {{ ansible_hostname }}"
