version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  vote:
    image: dockersamples/examplevotingapp_vote:latest
    container_name: vote
    ports:
      - "5000:80"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  worker:
    image: dockersamples/examplevotingapp_worker:latest
    container_name: worker
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - redis
      - db

  result:
    image: dockersamples/examplevotingapp_result:latest
    container_name: result
    ports:
      - "5001:80"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

volumes:
  db_data:
