version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}  # Optional for your setup
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

  java:
    build:
      context: ./java
    restart: always
    ports:
      - "8080:8080"
    environment:
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DATABASE}
    depends_on:
      - mongodb

  react:
    build:
      context: ./react
    restart: always
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
    depends_on:
      - java

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - react
      - java

volumes:
  mongodb_data:
