version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_ROOT_DATABASE: ${MONGO_DATABASE}
    volumes:
      - ./movie-data:/data/db  # volume binding (changed from /data/movies to /data/db)

  java:
    build:
      context: ./java
    restart: always
    ports:
      - "8080:8080"
    environment:
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_URI: ${MONGO_URL}  # Fixed variable name from MONGO_CLUSTER
    depends_on:
      - mongodb

  react:
    build:
      context: ./react
    restart: always
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
    depends_on:
      - java

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # volume binding
    depends_on:
      - react
      - java  # updated to ensure the service is correctly ordered
