version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_DATABASE=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
    volumes:
      - ./movie-data:/data/movies  # volume binding

  java:
    build:
        context: ./java
    restart: always
    ports:
        - "8080:8080"
    environment:
        - MONGO_DATABASE=${MONGO_USER}
        - MONGO_PASSWORD=${MONGO_PASSWORD}
        - MONGO_DATABASE=${MONGO_DATABASE}
        - MONGO_CLUSTER =${MONGO_CLUSTER}

    depends_on:
        - mongodb

  react:
    build:
        context: ./react
    restart: always
    ports:
        - "3000:3000"
    environment:
        - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}

    depends_on:
        - java

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # volume binding
    depends_on:
      - react
      - mongodb




