version: '3.8'

services:
  java:
    build:
      context: ./java
    restart: always
    ports:
      - "8080:8080"
    environment:
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@localhost:27017/${MONGO_DATABASE}


  react:
    build:
      context: ./react
    restart: always
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
    depends_on:
      - java

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - react
      - java

volumes:
  mongodb_data:
