services:
  db:
    image: arm64v8/mariadb:10.5
    container_name: wordpress-db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password01
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: password01
    networks:
      - wordpress-network

  wordpress:
    image: arm64v8/wordpress:latest
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: password01
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db
    networks:
      - wordpress-network

networks:
  wordpress-network:
    driver: bridge

volumes:
  db_data: {}
  wordpress_data: {}
