apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-storage
provisioner: kubernetes.io/aws-ebs  # The provisioner for AWS EBS
parameters:
  type: gp2  # General Purpose SSD
  fsType: ext4  # The file system type to format the volume with
reclaimPolicy: Delete  # Automatically delete the PV when the PVC is deleted


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
spec:
  storageClassName: standard-storage  # Reference to the StorageClass
  accessModes:
    - ReadWriteOnce  # Only one node can mount the volume
  resources:
    requests:
      storage: 5Gi  # Request 5Gi of storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-2
spec:
  storageClassName: standard-storage  # Reference to the StorageClass
  accessModes:
    - ReadWriteOnce  # Only one node can mount the volume
  resources:
    requests:
      storage: 8Gi  # Request 8Gi of storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2  # Create two replicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2  # Nginx container image
        ports:
        - containerPort: 80
        volumeMounts:
        - name: storage-1
          mountPath: /usr/share/nginx/html  # Mount path inside the container for pvc-1
        - name: storage-2
          mountPath: /var/log/nginx  # Mount path inside the container for pvc-2
      volumes:
      - name: storage-1
        persistentVolumeClaim:
          claimName: pvc-1  # Bind pvc-1 to storage-1
      - name: storage-2
        persistentVolumeClaim:
          claimName: pvc-2  # Bind pvc-2 to storage-2
