apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: delayed-binding-storage
provisioner: kubernetes.io/aws-ebs  # Provisioner for AWS EBS
volumeBindingMode: WaitForFirstConsumer  # Delayed binding until the Pod is scheduled
reclaimPolicy: Retain  # Retain the PV after PVC deletion
parameters:
  type: gp2  # General Purpose SSD
  fsType: ext4  # File system type

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-delayed-binding
spec:
  storageClassName: delayed-binding-storage  # Reference to the StorageClass
  accessModes:
    - ReadWriteOnce  # Only one node can mount the volume
  resources:
    requests:
      storage: 10Gi  # Request 10Gi of storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-delayed-binding
spec:
  replicas: 1  # Create a single replica
  selector:
    matchLabels:
      app: nginx-delayed
  template:
    metadata:
      labels:
        app: nginx-delayed
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2  # Nginx container image
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-storage
          mountPath: /usr/share/nginx/html  # Mount path inside the container
      volumes:
      - name: nginx-storage
        persistentVolumeClaim:
          claimName: pvc-delayed-binding  # Bind the PVC to this volume
